### ISSUE TITLE
failed with dnds_est.method ="YN"

### ISSUE THREAD

**Issue by lihongyi123** [HajkD/orthologr#4] opened 2017-02-23 22:31 UTC
Hi Hajk,
I have installed the package, and succeeded with the  dnds_est.method ="Comeron" and "Li", But failed  with the rests like "YN" or "MYN", the code are following:
`dNdS(query_file      = system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'),
     subject_file    = system.file('seqs/ortho_lyra_cds.fasta', package = 'orthologr'),
     ortho_detection = "RBH", 
     aa_aln_type     = "pairwise",
     aa_aln_tool     = "NW", 
     codon_aln_tool  = "pal2nal", 
     dnds_est.method = "YN", 
     comp_cores      = 1 ,
     kaks_calc_path  = "/home/lhy/software/KaKs_Calculator2.0/src/")
Building a new DB, current time: 02/24/2017 05:52:24
New DB name:   /tmp/RtmpaZIBhK/_blast_db/blastdb_ortho_lyra_cds.fasta_protein.fasta
New DB title:  blastdb_ortho_lyra_cds.fasta_protein.fasta
Sequence type: Protein
Deleted existing Protein BLAST database named /tmp/RtmpaZIBhK/_blast_db/blastdb_ortho_lyra_cds.fasta_protein.fasta
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 20 sequences in 0.00255609 seconds.

Building a new DB, current time: 02/24/2017 05:52:24
New DB name:   /tmp/RtmpaZIBhK/_blast_db/blastdb_ortho_thal_cds.fasta_protein.fasta
New DB title:  blastdb_ortho_thal_cds.fasta_protein.fasta
Sequence type: Protein
Deleted existing Protein BLAST database named /tmp/RtmpaZIBhK/_blast_db/blastdb_ortho_thal_cds.fasta_protein.fasta
Keep Linkouts: T
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 20 sequences in 0.00225496 seconds.
[1] "File successfully written to /tmp/RtmpaZIBhK/_alignment/pairwise_aln/q1_NW_AA.aln"
[1] "Codon Alignment successfully written in /tmp/RtmpaZIBhK/_alignment/codon_aln/q1_pal2nal.aln."
*****************************************************************
Function: Parse fasta file with aligned pairwise sequences into AXT file
Reference: Zhang Z, Li J, Zhao XQ, Wang J, Wong GK, Yu J: KaKs Calculator: Calculating Ka and Ks through model selection and model averaging. Genomics Proteomics Bioinformatics 2006 , 4:259-263. 
Web Link: Documentation, example and updates at <http://code.google.com/p/kaks-calculator>
*****************************************************************

Input file = /tmp/RtmpaZIBhK/_alignment/codon_aln/q1_pal2nal.aln
Opening the input file...
Reading sequences..................................................
Formatting AXT sequences...
Outputing AXT file: /tmp/RtmpaZIBhK/_calculation/q1_pal2nal.aln.axt

Mission accomplished.
sh: 1: KaKs_Calculator: not found
Error in value[[3L]](cond) : Something went wront with KaKs_Calculator.
/tmp/RtmpaZIBhK/_calculation/q1_pal2nal.aln.axt.kaks could not be read properly.
Besides: Warning message:
In file(file, "rt") :
  can not open '/tmp/RtmpaZIBhK/_calculation/q1_pal2nal.aln.axt.kaks': no such file`

If I use the KaKs_Calculator to calculate the da/ds of q1_pal2nal.aln.axt using "-c YN" or "MYN",  I can get the result correctly. 
The version of KaKs_Calculator is 2.0.
Thanks!

**Comment by HajkD** [comment] 2017-03-02 15:57
Hi Hongyi,

I am so sorry that I come back to you so late.

Thank you so much for pointing this shortcoming out to me. I will have a look at it and will try to fix the bug.

I will come back to you as soon as I fixed it.

Best wishes,
Hajk

**Comment by lihongyi123** [comment] 2017-03-02 17:38
Hi Hajk, I have find the problem may because  a wrong position of a bracket in the function of substitutionrate.R. But i am home and in the bed, so i will show you when i get up tomorrow. Thanks very much for the useful tool. Hongyi

**Comment by HajkD** [comment] 2017-03-02 17:40
Hi Hongyi,

wow that's perfect!!!!

Thank you so so much :)

I look forward to hearing from you tomorrow.

Good night,
Hajk

**Comment by lihongyi123** [comment] 2017-03-03 02:13
Hi Hajk
please check the following code in the substitutionrate.R:
` if (is.null(kaks_calc.params))
                                system(paste0(
                                        KaKs_Calculator,
                                        " -i ",
                                        file.path(
                                                tempdir(),
                                                "_calculation",
                                                paste0(file_name, ".axt")
                                        ),
                                        " -o ",
                                        file.path(
                                                tempdir(),
                                                "_calculation",
                                                paste0(file_name, ".axt.kaks")),
                                                " -m ",
                                                est.method
                                        
                                ))
                        
                        if (!is.null(kaks_calc.params))
                          print("1")
                                system(paste0(
                                        KaKs_Calculator,
                                        " -i ",
                                        file.path(
                                                tempdir(),
                                                "_calculation",
                                                paste0(file_name, ".axt")
                                        ),
                                        " -o ",
                                        file.path(
                                                tempdir(),
                                                "_calculation",
                                                paste0(file_name, ".axt.kaks")),
                                                " ",
                                                kaks_calc.params
                                        
                                ))`
where the ")"  have been moved  from line 350 to 347 and from 369 to 366.
It works when I load it directly into R  together with other codes.
By the way, I suggest to add "GMYN" into the vector kaks_calc_methods to support kaks_calculator v2.0.

Best wishes,
Hongyi

**Comment by HajkD** [comment] 2017-03-03 12:15
Hi Hongyi,

you were absolutely right. This major bug was caused by a misplaced ')'  in file.path(paste0() ...).

Thank you so so much for spotting it and making me aware of it. I truly appreciate it!

I now fixed the bug and pushed a new version of orthologr: https://github.com/HajkD/orthologr/commit/ba29812fb8e1129c7bc8e1716ea86b9bf4569b02

I also incorporated  the option "GMYN".

I documented the bug in the new NEWS file: https://github.com/HajkD/orthologr/blob/master/NEWS.md

Please let me know if you spot something else or if you think that it would be useful to add some additional functionality to orthologr.

It was a pleasure to collaborate with you :)

Best wishes,
Hajk

**Closed** 2017-03-03 14:21 UTC
